---
title       : DATA607 Team Project
subtitle    : Most Valuable Data Science Skills
author      : Team Ready 2 Rock
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {selfcontained, standalone, draft}
knit        : slidify::knit2slides
---

<style>
.title-slide {
  background-color: #FFFFFF; /* #EDE0CF; ; #CA9F9D*/
}
</style>

## Ready 2 Rock
- Anil Akyildirim
- Nicholas Chung
- Jai Jeffryes
- Tamiko Jenkins
- Joe Rovalino
- Sie Siong Wong

--- 

## Organize
- Slack private channel
- Skype
- GitHub: [https://github.com/pnojai/dskill](https://github.com/pnojai/dskill)
- Amazon Relational Database Service: [msds607.ckxhi71v1dqf.us-east-1.rds.amazonaws.com](msds607.ckxhi71v1dqf.us-east-1.rds.amazonaws.com)

--- 

## Lifecycle
- Formed team
- Explored articles
- Brainstormed approach
- Collected data
- Integrated data
- Concluded and reported

--- 

## Approach
- Assumption: if a data scientist is working, they possess the most valuable skills.
- Sample data scientists on LinkedIn.
- List of their skills.
- Count frequencies.
- Visualize and report.

### Nice to have
- Compare findings to 2018 findings by analyst Jeff Hale.

---

## Data Collection
- Bullet about scraping.

--- 

## Data integration
- MySQL on AWS.
- Data frames to MySQL.

--- 

## Analysis and conclusion
- What graphs.
- Relevant bullets.
- Conclusion.
- (One or two relevant plots?)
- (One summary report?)

--- 

## Achievements
- Team self-organization.
- Containment of scope.
- Fulfillment of minimum release.

---

## Version 2.0
- Next questions. (What else we could have explored.)
- Articles and resources we liked.
  - Jeff Hale's analysis on Medium: [https://towardsdatascience.com/the-most-in-demand-skills-for-data-scientists-4a4a8db896db](https://towardsdatascience.com/the-most-in-demand-skills-for-data-scientists-4a4a8db896db).
  - PayScale: [https://www.payscale.com](https://www.payscale.com).

---

## Notes from Anil's draft.
- Conclusion
- Use Cases (Best possible use cases for the study)
- Load Libraries (Load and install all the libraries)
- Data Collection
  - Data Sources (explain the data sources)
  - About Data Sets (variable descriptions, our collection method and relational database set up.)
  - Load Data to R (load the data set to R)

- Data Wrangling
  - Tidy Data (if required)
  - Identify and Handle Missing Values (if required)
  - Correct Data Formats (if required)
  - Data Standardization, Normalization (if required)

- Data Analysis and Exploration
  - Summary and Structure of the data (explore each variable and summary of the dataset)
  - Data Visualization 
  - Correlation and distribution

- Conclusion
- References
- Appendix (optional)
